/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  connection_action: () => import("@/views/connection/action/index.vue"),
  connection_default: () => import("@/views/connection/default/index.vue"),
  database_action: () => import("@/views/database/action/index.vue"),
  database_default: () => import("@/views/database/default/index.vue"),
  home: () => import("@/views/home/index.vue"),
  industria_connection_action: () => import("@/views/industria/connection/action/index.vue"),
  industria_connection_default: () => import("@/views/industria/connection/default/index.vue"),
  industria_task_action: () => import("@/views/industria/task/action/index.vue"),
  industria_task_default: () => import("@/views/industria/task/default/index.vue"),
  manage_authorize_action: () => import("@/views/manage/authorize/action/index.vue"),
  manage_authorize_default: () => import("@/views/manage/authorize/default/index.vue"),
  manage_config: () => import("@/views/manage/config/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  message_action: () => import("@/views/message/action/index.vue"),
  message_default: () => import("@/views/message/default/index.vue"),
  monitor_action: () => import("@/views/monitor/action/index.vue"),
  monitor_default: () => import("@/views/monitor/default/index.vue"),
  pending: () => import("@/views/pending/index.vue"),
  suspended: () => import("@/views/suspended/index.vue"),
  tasklog_default: () => import("@/views/tasklog/default/index.vue"),
  tasklog_details: () => import("@/views/tasklog/details/[id].vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  webapi_action: () => import("@/views/webapi/action/index.vue"),
  webapi_default: () => import("@/views/webapi/default/index.vue"),
};
