/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'connection',
    path: '/connection',
    component: 'layout.base',
    meta: {
      title: 'connection',
      i18nKey: 'route.connection'
    },
    children: [
      {
        name: 'connection_action',
        path: '/connection/action',
        component: 'view.connection_action',
        meta: {
          title: 'connection_action',
          i18nKey: 'route.connection_action'
        }
      },
      {
        name: 'connection_default',
        path: '/connection/default',
        component: 'view.connection_default',
        meta: {
          title: 'connection_default',
          i18nKey: 'route.connection_default'
        }
      }
    ]
  },
  {
    name: 'database',
    path: '/database',
    component: 'layout.base',
    meta: {
      title: 'database',
      i18nKey: 'route.database'
    },
    children: [
      {
        name: 'database_action',
        path: '/database/action',
        component: 'view.database_action',
        meta: {
          title: 'database_action',
          i18nKey: 'route.database_action'
        }
      },
      {
        name: 'database_default',
        path: '/database/default',
        component: 'view.database_default',
        meta: {
          title: 'database_default',
          i18nKey: 'route.database_default'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'industria',
    path: '/industria',
    component: 'layout.base',
    meta: {
      title: 'industria',
      i18nKey: 'route.industria'
    },
    children: [
      {
        name: 'industria_action',
        path: '/industria/action',
        component: 'view.industria_action',
        meta: {
          title: 'industria_action',
          i18nKey: 'route.industria_action'
        }
      },
      {
        name: 'industria_default',
        path: '/industria/default',
        component: 'view.industria_default',
        meta: {
          title: 'industria_default',
          i18nKey: 'route.industria_default'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_authorize',
        path: '/manage/authorize',
        meta: {
          title: 'manage_authorize',
          i18nKey: 'route.manage_authorize'
        },
        children: [
          {
            name: 'manage_authorize_action',
            path: '/manage/authorize/action',
            component: 'view.manage_authorize_action',
            meta: {
              title: 'manage_authorize_action',
              i18nKey: 'route.manage_authorize_action'
            }
          },
          {
            name: 'manage_authorize_default',
            path: '/manage/authorize/default',
            component: 'view.manage_authorize_default',
            meta: {
              title: 'manage_authorize_default',
              i18nKey: 'route.manage_authorize_default'
            }
          }
        ]
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'message',
    path: '/message',
    component: 'layout.base$view.message',
    meta: {
      title: 'message',
      i18nKey: 'route.message'
    }
  },
  {
    name: 'pending',
    path: '/pending',
    component: 'layout.base$view.pending',
    meta: {
      title: 'pending',
      i18nKey: 'route.pending'
    }
  },
  {
    name: 'suspended',
    path: '/suspended',
    component: 'layout.base$view.suspended',
    meta: {
      title: 'suspended',
      i18nKey: 'route.suspended'
    }
  },
  {
    name: 'tasklog',
    path: '/tasklog',
    component: 'layout.base$view.tasklog',
    meta: {
      title: 'tasklog',
      i18nKey: 'route.tasklog'
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  },
  {
    name: 'webapi',
    path: '/webapi',
    component: 'layout.base',
    meta: {
      title: 'webapi',
      i18nKey: 'route.webapi'
    },
    children: [
      {
        name: 'webapi_action',
        path: '/webapi/action',
        component: 'view.webapi_action',
        meta: {
          title: 'webapi_action',
          i18nKey: 'route.webapi_action'
        }
      },
      {
        name: 'webapi_default',
        path: '/webapi/default',
        component: 'view.webapi_default',
        meta: {
          title: 'webapi_default',
          i18nKey: 'route.webapi_default'
        }
      }
    ]
  }
];
